name: electricity_shop_mobile
description: "ElectricityShop mobile app for browsing and purchasing electrical products."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  
  # API integration
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  
  # Local storage
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  
  # UI
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # Pagination
  infinite_scroll_pagination: ^5.0.0
  
  # Authentication
  jwt_decoder: ^2.0.1
  
  # Utilities
  intl: ^0.20.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
